// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy3Kj2RLuiRfyET8iSmhdftUGgEXHFtN0',
    appId: '1:237272805388:web:29be8b28a90c81ba72be29',
    messagingSenderId: '237272805388',
    projectId: 'foodgo-78f27',
    authDomain: 'foodgo-78f27.firebaseapp.com',
    storageBucket: 'foodgo-78f27.firebasestorage.app',
    measurementId: 'G-K6LT2VTSVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLFib13tK-uzIpDV5CeV86xxu18LLolPU',
    appId: '1:237272805388:android:43f06c41faa0df9f72be29',
    messagingSenderId: '237272805388',
    projectId: 'foodgo-78f27',
    storageBucket: 'foodgo-78f27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ojHbzIm0ojYtpMCxTeX-yn1y9khns1U',
    appId: '1:237272805388:ios:e608dd9623f6a42672be29',
    messagingSenderId: '237272805388',
    projectId: 'foodgo-78f27',
    storageBucket: 'foodgo-78f27.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ojHbzIm0ojYtpMCxTeX-yn1y9khns1U',
    appId: '1:237272805388:ios:e608dd9623f6a42672be29',
    messagingSenderId: '237272805388',
    projectId: 'foodgo-78f27',
    storageBucket: 'foodgo-78f27.firebasestorage.app',
    iosBundleId: 'com.example.foodgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy3Kj2RLuiRfyET8iSmhdftUGgEXHFtN0',
    appId: '1:237272805388:web:26626f3088d2b5e972be29',
    messagingSenderId: '237272805388',
    projectId: 'foodgo-78f27',
    authDomain: 'foodgo-78f27.firebaseapp.com',
    storageBucket: 'foodgo-78f27.firebasestorage.app',
    measurementId: 'G-YNJDTL1XTS',
  );
}
